# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(982, 1190)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_1_horizontalLayout = QtWidgets.QHBoxLayout()
        self.main_1_horizontalLayout.setObjectName("main_1_horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_1_horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.main_1_horizontalLayout)
        self.main_2_horizontalLayout = QtWidgets.QHBoxLayout()
        self.main_2_horizontalLayout.setSpacing(0)
        self.main_2_horizontalLayout.setObjectName("main_2_horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(190, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_2_horizontalLayout.addItem(spacerItem1)
        self.left_widget = QtWidgets.QWidget(Form)
        self.left_widget.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.left_widget.setObjectName("left_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_2_horizontalLayout.addWidget(self.left_widget)
        self.main_widget = QtWidgets.QWidget(Form)
        self.main_widget.setStyleSheet("background-color: rgb(11,11,11);")
        self.main_widget.setObjectName("main_widget")
        self.main_grid_Layout = QtWidgets.QGridLayout(self.main_widget)
        self.main_grid_Layout.setContentsMargins(9, 9, 9, 9)
        self.main_grid_Layout.setObjectName("main_grid_Layout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.main_grid_Layout.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mange_widget = QtWidgets.QWidget(self.main_widget)
        self.mange_widget.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.mange_widget.setObjectName("mange_widget")
        self.gridLayout_4.addWidget(self.mange_widget, 1, 1, 1, 1)
        self.all_widget = QtWidgets.QWidget(self.main_widget)
        self.all_widget.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.all_widget.setObjectName("all_widget")
        self.all_grid_Layout = QtWidgets.QGridLayout(self.all_widget)
        self.all_grid_Layout.setContentsMargins(0, 0, 0, 0)
        self.all_grid_Layout.setObjectName("all_grid_Layout")
        self.model_widget = QtWidgets.QWidget(self.all_widget)
        self.model_widget.setStyleSheet("\n"
"\n"
"background-color:  rgb(11,11,11);")
        self.model_widget.setObjectName("model_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.model_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(5, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(self.model_widget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border-bottom: 3px solid  rgb(72, 72, 72);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.model_widget)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setStyleSheet("border-style:solid;\n"
"border-color:rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:12px;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(11,11,11);\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 31))
        self.label_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 71, 31))
        self.label_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 111, 31))
        self.label_4.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 101, 31))
        self.label_5.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 91, 31))
        self.label_6.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.model_widget)
        self.groupBox_2.setStyleSheet("border-style:solid;\n"
"border-color:rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:12px;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(11,11,11);\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.label_7.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 111, 31))
        self.label_8.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 71, 31))
        self.label_9.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 71, 31))
        self.label_10.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 140, 81, 31))
        self.label_11.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.groupBox_2, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 3, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.all_grid_Layout.addWidget(self.model_widget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.all_widget, 0, 0, 1, 1)
        self.main_grid_Layout.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.main_2_horizontalLayout.addWidget(self.main_widget)
        self.verticalLayout.addLayout(self.main_2_horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Settings"))
        self.groupBox.setTitle(_translate("Form", "User Details"))
        self.label_2.setText(_translate("Form", "Name :"))
        self.label_3.setText(_translate("Form", "Address :"))
        self.label_4.setText(_translate("Form", "Company Name :"))
        self.label_5.setText(_translate("Form", "Phone Number :"))
        self.label_6.setText(_translate("Form", "Email Address :"))
        self.groupBox_2.setTitle(_translate("Form", "License Details"))
        self.label_7.setText(_translate("Form", "License Type :"))
        self.label_8.setText(_translate("Form", "Registration Date :"))
        self.label_9.setText(_translate("Form", "Expiry Date :"))
        self.label_10.setText(_translate("Form", "Qty :"))
        self.label_11.setText(_translate("Form", "System MAC :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
