# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1398, 709)
        self.main_frame = QtWidgets.QFrame(Form)
        self.main_frame.setGeometry(QtCore.QRect(180, 70, 1221, 641))
        self.main_frame.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.sub_frame = QtWidgets.QFrame(self.main_frame)
        self.sub_frame.setGeometry(QtCore.QRect(0, 0, 1211, 71))
        self.sub_frame.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.sub_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sub_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sub_frame.setObjectName("sub_frame")
        self.label_3 = QtWidgets.QLabel(self.sub_frame)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 181, 21))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.language_btn = QtWidgets.QPushButton(self.sub_frame)
        self.language_btn.setGeometry(QtCore.QRect(830, 40, 141, 31))
        self.language_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.language_btn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.language_btn.setObjectName("language_btn")
        self.history_sub2_btn = QtWidgets.QPushButton(self.sub_frame)
        self.history_sub2_btn.setGeometry(QtCore.QRect(670, 40, 141, 31))
        self.history_sub2_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_sub2_btn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.history_sub2_btn.setObjectName("history_sub2_btn")
        self.evs_btn = QtWidgets.QPushButton(self.sub_frame)
        self.evs_btn.setGeometry(QtCore.QRect(510, 40, 141, 31))
        self.evs_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.evs_btn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.evs_btn.setObjectName("evs_btn")
        self.physics_btn = QtWidgets.QPushButton(self.sub_frame)
        self.physics_btn.setGeometry(QtCore.QRect(350, 40, 141, 31))
        self.physics_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.physics_btn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.physics_btn.setObjectName("physics_btn")
        self.maths_btn = QtWidgets.QPushButton(self.sub_frame)
        self.maths_btn.setGeometry(QtCore.QRect(190, 40, 141, 31))
        self.maths_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maths_btn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.maths_btn.setObjectName("maths_btn")
        self.biology_btn = QtWidgets.QPushButton(self.sub_frame)
        self.biology_btn.setGeometry(QtCore.QRect(30, 40, 141, 31))
        self.biology_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.biology_btn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.biology_btn.setObjectName("biology_btn")
        self.video_frame = QtWidgets.QFrame(self.main_frame)
        self.video_frame.setGeometry(QtCore.QRect(30, 90, 651, 271))
        self.video_frame.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.video_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_frame.setObjectName("video_frame")
        self.bottom_frame = QtWidgets.QFrame(self.main_frame)
        self.bottom_frame.setGeometry(QtCore.QRect(30, 410, 651, 201))
        self.bottom_frame.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.right_frame = QtWidgets.QFrame(self.main_frame)
        self.right_frame.setGeometry(QtCore.QRect(730, 90, 471, 521))
        self.right_frame.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.left_frame = QtWidgets.QFrame(Form)
        self.left_frame.setGeometry(QtCore.QRect(0, 70, 181, 641))
        self.left_frame.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.home_btn = QtWidgets.QPushButton(self.left_frame)
        self.home_btn.setGeometry(QtCore.QRect(0, 0, 181, 31))
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:70px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon)
        self.home_btn.setIconSize(QtCore.QSize(15, 15))
        self.home_btn.setCheckable(False)
        self.home_btn.setObjectName("home_btn")
        self.history_btn = QtWidgets.QPushButton(self.left_frame)
        self.history_btn.setGeometry(QtCore.QRect(0, 80, 181, 31))
        self.history_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:70px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_btn.setIcon(icon1)
        self.history_btn.setIconSize(QtCore.QSize(55, 55))
        self.history_btn.setObjectName("history_btn")
        self.popular_btn = QtWidgets.QPushButton(self.left_frame)
        self.popular_btn.setGeometry(QtCore.QRect(0, 40, 181, 31))
        self.popular_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.popular_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:60px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/popular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.popular_btn.setIcon(icon2)
        self.popular_btn.setIconSize(QtCore.QSize(15, 15))
        self.popular_btn.setAutoDefault(False)
        self.popular_btn.setDefault(False)
        self.popular_btn.setFlat(False)
        self.popular_btn.setObjectName("popular_btn")
        self.categories_btn = QtWidgets.QPushButton(self.left_frame)
        self.categories_btn.setGeometry(QtCore.QRect(0, 120, 181, 31))
        self.categories_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.categories_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:40px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/categories.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.categories_btn.setIcon(icon3)
        self.categories_btn.setIconSize(QtCore.QSize(35, 35))
        self.categories_btn.setObjectName("categories_btn")
        self.favorites_btn = QtWidgets.QPushButton(self.left_frame)
        self.favorites_btn.setGeometry(QtCore.QRect(0, 160, 181, 31))
        self.favorites_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.favorites_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:50px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/favorites.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.favorites_btn.setIcon(icon4)
        self.favorites_btn.setIconSize(QtCore.QSize(40, 40))
        self.favorites_btn.setObjectName("favorites_btn")
        self.label_2 = QtWidgets.QLabel(self.left_frame)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 131, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 italic 16pt \"Perpetua\";\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.mathematics_btn = QtWidgets.QPushButton(self.left_frame)
        self.mathematics_btn.setGeometry(QtCore.QRect(0, 220, 181, 31))
        self.mathematics_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mathematics_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:30px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/mathematics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mathematics_btn.setIcon(icon5)
        self.mathematics_btn.setIconSize(QtCore.QSize(40, 40))
        self.mathematics_btn.setObjectName("mathematics_btn")
        self.science_btn = QtWidgets.QPushButton(self.left_frame)
        self.science_btn.setGeometry(QtCore.QRect(0, 260, 181, 31))
        self.science_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.science_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:65px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/science.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.science_btn.setIcon(icon6)
        self.science_btn.setIconSize(QtCore.QSize(40, 40))
        self.science_btn.setObjectName("science_btn")
        self.arts_btn = QtWidgets.QPushButton(self.left_frame)
        self.arts_btn.setGeometry(QtCore.QRect(0, 300, 181, 31))
        self.arts_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.arts_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:80px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/arts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arts_btn.setIcon(icon7)
        self.arts_btn.setIconSize(QtCore.QSize(40, 40))
        self.arts_btn.setObjectName("arts_btn")
        self.history_sub_btn = QtWidgets.QPushButton(self.left_frame)
        self.history_sub_btn.setGeometry(QtCore.QRect(0, 340, 181, 31))
        self.history_sub_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_sub_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:60px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/history_sub.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_sub_btn.setIcon(icon8)
        self.history_sub_btn.setIconSize(QtCore.QSize(40, 40))
        self.history_sub_btn.setObjectName("history_sub_btn")
        self.label_4 = QtWidgets.QLabel(self.left_frame)
        self.label_4.setGeometry(QtCore.QRect(10, 380, 101, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 16pt \"Perpetua\";")
        self.label_4.setObjectName("label_4")
        self.standards_frame = QtWidgets.QFrame(self.left_frame)
        self.standards_frame.setGeometry(QtCore.QRect(10, 400, 151, 231))
        self.standards_frame.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.standards_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.standards_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.standards_frame.setObjectName("standards_frame")
        self.top_frame = QtWidgets.QFrame(Form)
        self.top_frame.setGeometry(QtCore.QRect(0, 0, 1401, 71))
        self.top_frame.setStyleSheet("background-color: rgb(36, 36, 36);\n"
"/*border-bottom: 3px solid red;\n"
"")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.label = QtWidgets.QLabel(self.top_frame)
        self.label.setGeometry(QtCore.QRect(30, 20, 151, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 19pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.import_btn = QtWidgets.QPushButton(self.top_frame)
        self.import_btn.setGeometry(QtCore.QRect(1170, 20, 151, 31))
        self.import_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.import_btn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.import_btn.setObjectName("import_btn")
        self.setting_btn = QtWidgets.QPushButton(self.top_frame)
        self.setting_btn.setGeometry(QtCore.QRect(1320, 20, 51, 31))
        self.setting_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting_btn.setStyleSheet("background-color: rgb(36, 36, 36);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px")
        self.setting_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_btn.setIcon(icon9)
        self.setting_btn.setIconSize(QtCore.QSize(60, 60))
        self.setting_btn.setObjectName("setting_btn")
        self.search_edit = QtWidgets.QLineEdit(self.top_frame)
        self.search_edit.setGeometry(QtCore.QRect(190, 20, 361, 31))
        self.search_edit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"background-color:rgb(11, 11, 11);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:15px;\n"
"\n"
"padding:6px\n"
"}\n"
"QLineEdit:focus{\n"
"\n"
"    border-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.search_edit.setFrame(True)
        self.search_edit.setObjectName("search_edit")
        self.search_btn = QtWidgets.QPushButton(self.top_frame)
        self.search_btn.setGeometry(QtCore.QRect(560, 20, 41, 31))
        self.search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}")
        self.search_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon10)
        self.search_btn.setObjectName("search_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Explore by Subjects"))
        self.language_btn.setText(_translate("Form", "LANGUAGE"))
        self.history_sub2_btn.setText(_translate("Form", "HISTORY"))
        self.evs_btn.setText(_translate("Form", "EVS"))
        self.physics_btn.setText(_translate("Form", "PHYSICS"))
        self.maths_btn.setText(_translate("Form", "MATHS"))
        self.biology_btn.setText(_translate("Form", "BIOLOGY"))
        self.home_btn.setText(_translate("Form", "   Home"))
        self.history_btn.setText(_translate("Form", " History "))
        self.popular_btn.setText(_translate("Form", "   Popular"))
        self.categories_btn.setText(_translate("Form", "  Categories "))
        self.favorites_btn.setText(_translate("Form", "  Favorites "))
        self.label_2.setText(_translate("Form", "CATEGORIES"))
        self.mathematics_btn.setText(_translate("Form", "   Mathematics "))
        self.science_btn.setText(_translate("Form", "   Science "))
        self.arts_btn.setText(_translate("Form", "   Arts "))
        self.history_sub_btn.setText(_translate("Form", "   History "))
        self.label_4.setText(_translate("Form", "STANDARDS"))
        self.label.setText(_translate("Form", "Education 3D"))
        self.import_btn.setText(_translate("Form", "Import Models"))
        self.search_edit.setPlaceholderText(_translate("Form", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
