# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importmodels.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1388, 709)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(180, 70, 1221, 641))
        self.frame_3.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1211, 71))
        self.frame_4.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 10, 1211, 51))
        self.frame_5.setStyleSheet("\n"
"\n"
"border-bottom-style:outset;\n"
"border-width:1px;\n"
"background-color: rgb(11, 11, 11);\n"
"border-color:   rgb(172, 172, 172);\n"
"color: rgb(90, 90, 90);\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(470, 10, 271, 31))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border-width:0px;\n"
"border-color:   rgb(172, 172, 172);")
        self.label.setObjectName("label")
        self.internet_btn = QtWidgets.QPushButton(self.frame_3)
        self.internet_btn.setGeometry(QtCore.QRect(340, 170, 221, 201))
        self.internet_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.internet_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(11, 11, 11);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:5px;\n"
"border-radius:15px;\n"
"border-color:  rgb(255, 255, 255);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}")
        self.internet_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/741_page-0001-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.internet_btn.setIcon(icon)
        self.internet_btn.setIconSize(QtCore.QSize(500, 500))
        self.internet_btn.setObjectName("internet_btn")
        self.cd_btn = QtWidgets.QPushButton(self.frame_3)
        self.cd_btn.setGeometry(QtCore.QRect(610, 170, 221, 201))
        self.cd_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cd_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(11, 11, 11);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:5px;\n"
"border-radius:15px;\n"
"border-color:  rgb(255, 255, 255);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}")
        self.cd_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/741_page-0002-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cd_btn.setIcon(icon1)
        self.cd_btn.setIconSize(QtCore.QSize(500, 500))
        self.cd_btn.setObjectName("cd_btn")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(420, 390, 71, 21))
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(690, 390, 71, 21))
        self.label_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(410, 100, 351, 21))
        self.label_6.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Import new Models / Videos..."))
        self.label_3.setText(_translate("Form", "Internet"))
        self.label_5.setText(_translate("Form", "CD / USB"))
        self.label_6.setText(_translate("Form", "How would you like to import new Models?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
