# Generated by Django 4.0.4 on 2022-05-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('age', models.TextField(max_length=100)),
            ],
        ),
    ]
