# Generated by Django 4.0.4 on 2022-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.TextField(max_length=30),
        ),
    ]
