# Generated by Django 4.0.4 on 2022-06-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='city',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='first_name',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='user_name',
        ),
    ]
