# Generated by Django 4.0.4 on 2022-06-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_city_signup_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Name',
            new_name='name',
        ),
    ]
