# Generated by Django 4.0.4 on 2022-06-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_signup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
