# Generated by Django 4.0.4 on 2022-06-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gmail',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
